In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
a + 1

array([2, 3, 4, 5])

In [4]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [5]:
2*a

array([2, 4, 6, 8])

In [6]:
b = np.ones(4) + 1

In [7]:
a - b

array([-1.,  0.,  1.,  2.])

In [8]:
a * b

array([2., 4., 6., 8.])

In [9]:
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [10]:
a = np.arange(10000)

In [11]:
%timeit a + 1 

22 µs ± 2.66 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [12]:
l = range(10000)

In [13]:
%timeit [i+1 for i in l]

1.64 ms ± 149 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [15]:
a == b

array([False,  True, False,  True])

In [16]:
a>b

array([False, False,  True, False])

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [18]:
np.array_equal(a, b)

False

In [19]:
np.array_equal(a, c)

True