In [25]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
a + 1

array([2, 3, 4, 5])

In [4]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [5]:
2*a

array([2, 4, 6, 8])

In [6]:
b = np.ones(4) + 1

In [7]:
a - b

array([-1.,  0.,  1.,  2.])

In [8]:
a * b

array([2., 4., 6., 8.])

In [9]:
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [10]:
a = np.arange(10000)

In [11]:
%timeit a + 1 

22 µs ± 2.66 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [12]:
l = range(10000)

In [13]:
%timeit [i+1 for i in l]

1.64 ms ± 149 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [15]:
a == b

array([False,  True, False,  True])

In [16]:
a>b

array([False, False,  True, False])

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [18]:
np.array_equal(a, b)

False

In [19]:
np.array_equal(a, c)

True

In [20]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

In [21]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [22]:
np.logical_and(a, b)

array([ True, False, False, False])

In [23]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [26]:
np.log(a)

C:\Users\Asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [27]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [28]:
a = np.arange(4)
a + np.array([1, 2]) 

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [29]:
a = np.triu(np.ones((3, 3)), 1) 

In [30]:
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [31]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [32]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [33]:
x.sum()

10

In [34]:
x = np.array([[1, 1], [2, 2]])

In [35]:
x

array([[1, 1],
       [2, 2]])

In [36]:
x.sum(axis=0)

array([3, 3])

In [37]:
x.sum(axis=1)

array([2, 4])

In [38]:
x[:, 0].sum(), x[:, 1].sum()

(3, 3)

In [39]:
x.sum(axis=1)

array([2, 4])

In [40]:
x[0, :].sum(), x[1, :].sum()

(2, 4)

In [41]:
x = np.random.rand(2, 2, 2)
x.sum(axis=2)[0, 1]

0.680779620861216

In [42]:
x[0, 1, :].sum() 

0.680779620861216

In [44]:
x = np.array([1, 3, 2])
x.min()

1

In [45]:
x.max()

3

In [46]:
x.argmin()

0

In [47]:
x.argmax()

1